### ISSUE TITLE
Maya 2025 with Qt6 support fails due to usage of `QDesktopWidget`

### ISSUE THREAD

**Issue by BigRoy** [abstractfactory/maya-capture#94]
### Issue

Maya 2025 has been released with Qt6 / PySide6.

[This line](https://github.com/abstractfactory/maya-capture/blob/f83fbea4f49d8a58f17c5de53bf8808f1c3ce35a/capture.py#L801) fails in Maya 2025.
```python
Traceback (most recent call last):
  File "C:\Users\murph\AppData\Local\Ynput\AYON\dependency_packages\ayon_2402141620_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\plugins\publish\extract_playblast.py", line 60, in process
    lib.render_capture_preset(preset)
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\api\lib.py", line 239, in render_capture_preset
    path = capture.capture(log=self.log, **preset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 169, in capture
    with _independent_panel(width=width + padding,
  File "C:\Program Files\Autodesk\Maya2025\Python\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 614, in _independent_panel
    screen_width, screen_height = _get_screen_size()
                                  ^^^^^^^^^^^^^^^^^^
  File "c:\Users\murph\Documents\Ayon\REPO\ayon-core\client\ayon_core\hosts\maya\vendor\python\capture.py", line 872, in _get_screen_size
    rect = QtWidgets.QDesktopWidget().screenGeometry(-1)
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qtpy.QtWidgets' has no attribute 'QDesktopWidget'
```
_Note that this log is not directly from `capture.py` but from something that vendorizes it. Issue was reported [here](https://github.com/ynput/ayon-core/pull/293#pullrequestreview-1966125035)._

It is because [`QDesktopWidget` has been removed in `Qt6`](https://doc.qt.io/qt-6/widgets-changes-qt6.html#qdesktopwidget-and-qapplication-desktop) and thus `capture.py` would need to be updated.

According to those docs we should instead use `QScreen` for similar features.

**Comment by mottosso** [comment]
Thanks for reporting Roy. Up for patching it?

**Comment by BigRoy** [comment]
> Thanks for reporting Roy. Up for patching it?

Not using Maya 2025 myself just yet - and working on some other stuff somewhere through end of next week. So likely won't be looking into this before then.

**Comment by BigRoy** [comment]
@mottosso it seems a fix got proposed [here](https://github.com/ynput/ayon-core/commit/d68664b20b22dbf9051d78ec19ac4653e3f97b0d) which you may be able to use as reference. Or maybe @antirotor is able to contribute upstream to this repository?
